### ISSUE TITLE
fail to use pykafka 1.0.3 in python 2.6.6 

### ISSUE THREAD

**Issue by zhynxn** [Parsely/pykafka#184]
I use pip install pykafka, and encountered problems. 
python version  2.6.6 
pykafka version 1.0.3 

I am not sure it is python version issue. please help. 

[root@hadoop-av1 ~]# easy_install pykafka
Searching for pykafka
Reading http://pypi.python.org/simple/pykafka/
Best match: pykafka 1.0.3
Downloading https://pypi.python.org/packages/source/p/pykafka/pykafka-1.0.3.tar.gz#md5=9cd61e00e76b2168245392102ca75e16
Processing pykafka-1.0.3.tar.gz
Running pykafka-1.0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-iwDT0r/pykafka-1.0.3/egg-dist-tmp-XfewG4
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/pykafka/simpleconsumer.py', 160, 35, '                                for p in partitions}\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/pykafka-1.0.3-py2.6.egg/pykafka/simpleconsumer.py', 160, 35, '                                for p in partitions}\n'))

Adding pykafka 1.0.3 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/pykafka-1.0.3-py2.6.egg
Processing dependencies for pykafka
Finished processing dependencies for pykafka
[root@hadoop-av1 ~]# python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykafka
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pykafka-1.0.3-py2.6.egg/pykafka/__init__.py", line 2, in <module>
    from simpleconsumer import SimpleConsumer
  File "/usr/lib/python2.6/site-packages/pykafka-1.0.3-py2.6.egg/pykafka/simpleconsumer.py", line 160
    for p in partitions}
      ^
SyntaxError: invalid syntax
>>>

**Comment by emmett9001** [comment]
Hi @zhynxn, thanks for filing this. Pykafka 1.0.3 is only compatible with python 2.7. This error is happening because python 2.6 doesn't have dictionary comprehensions, which the SimpleConsumer uses.

If you can upgrade to python 2.7, I recommend doing so.

**Comment by emmett9001** [comment]
I've fixed some basic issues related to running PyKafka under python 2.6 on master. You can test the changes by cloning this repository. I haven't gotten the tests to work, since they use new features of the `os` and `subprocess` modules, but you may have better luck running a consumer or producer under python 2.6. However, bear in mind that we don't officially support that version.

**Comment by zhynxn** [comment]
thank you so much for quick support! 

i notice it is python version compatibility issue. i will try python2.7 in my system

**Comment by emmett9001** [comment]
No problem! Hopefully that works for you. If you have any other problems don't hesitate to file them here.

**Comment by zhynxn** [comment]
Hello Emmett,
Thank you for quick help.
I have questions about pykafka usage.

1) When producer send a message, how do I know it is successful or failed.
I try to check return code, so I can resend the message if failed.

2) When I use consumer, I tried the consumer.stop(), however I still get
use consumer.consume() to get message. (Of course, I set auto_start= False)

3) How to disconnect the consumer from topic? When I stop the consumer, I
need to remove consumer from registration. So I can have another consumer
connect to topic.

Thanks,
Yanxin

On Fri, Jun 19, 2015 at 11:17 AM, Emmett J. Butler <notifications@github.com

**Comment by emmett9001** [comment]
Hi,

1. If the producer encounters an error, it will [log it as a warning](https://github.com/Parsely/pykafka/blob/master/pykafka/producer.py#L157-L175) or in some cases [raise an exception](https://github.com/Parsely/pykafka/blob/master/pykafka/producer.py#L194). The producer handles retrying failed messages, so you can simply produce inside of a `try...except` like this:
```
try:
    producer.produce(messages)
except ProduceFailureError:
    deal_with_error()
```

2. When you call `consumer.stop()`, the consumer's fetch worker thread is [halted](https://github.com/Parsely/pykafka/blob/master/pykafka/simpleconsumer.py#L272-L273). This means that it will stop making requests to the kafka server for more messages. However, it is possible (and likely) that after a call to `stop()`, the consumer's internal queues will still contain messages that were fetched before `stop()` was called. Thus, you will still be able to call `consumer.consume()` until the queues are empty. If you want to be certain that you've consumed all of the messages that have been fetched, you can set the `consumer_timeout_ms` kwarg to some small number greater than zero and call `consume(block=True)` 
until it returns `None`.

3. I'm not certain what you mean in this question. The `BalancedConsumer` is the only type of pykafka consumer that registers itself in ZooKeeper. If you want to consume a topic with multiple processes, you can use several `BalancedConsumers` (one in each process) all sharing the same `consumer_group` argument. See the documentation on `BalancedConsumer` [here](http://pykafka.readthedocs.org/en/latest/api/balancedconsumer.html).

**Comment by zhynxn** [comment]
Thanks Emmett for quick answer. I modify my code based on that.

For my 3rd question, i am thinking instead of stop the program, I want to
disconnect gracefully the kafka client connection. However, I do not find
it in document.

**Comment by emmett9001** [comment]
@zhynxn There is actually no need to gracefully disconnect the `KafkaClient` since it doesn't maintain a persistent connection. It communicates with the kafka server on a request-response basis, so every time a function on `KafkaClient` returns, it's safe to deallocate the object.
