### ISSUE TITLE
Thread leakages in simple consumer and producer

### ISSUE THREAD

**Issue by zsimpson** [Parsely/pykafka#255]
I have a program which creates one of my own threads when a certain call happens. That thread of mine creates a simpleconsumer.

The def run() of my thread does something like this:

```
	topic = kafka_client.topics['test_topic']
	consumer = topic.get_simple_consumer( 'group_id' )
```

Note that `kafka_client` is global -- outside of my thread. That is, there is only one of them for all threads. But, consumer is local: there's one per thread.  When my thread's run() stops cleanly it calls:

```
	consumer.stop()
```

Yet when I look at the thread count I see that it grows by one every time I start and stop one of my threads.  If I take out the call to get the consumer then it doesn't. It appears as though there is a thread leak in the simple_consumer.

**Comment by emmett9001** [comment]
Thanks @zsimpson - we haven't done any testing of running a consumer on a non-main thread yet. When I get a chance, I'll try setting up a test case to see if I can replicate this. What are you using to count threads?

**Comment by zsimpson** [comment]
I'm using threading.active_count()

**Comment by emmett9001** [comment]
@zsimpson Here's the [messy script](https://gist.github.com/emmett9001/ad8c8a1ab66325887f5b) I used to test this, and here's a [possible solution](https://github.com/Parsely/pykafka/pull/256). It would be great if you could try the patch against your use case and see how it works. Note that it's normal for the thread count to increase by exactly one after starting and stopping N consumers on the same client - when one consumer opens the offsets channel connection on the broker, it stays open for the lifetime of that `Broker` (keeping the thread alive). The script running against the patched version demonstrates that even if you start twenty consumers concurrently and then stop them all, the total thread count has only increased by one (the expected behavior).

**Comment by zsimpson** [comment]
BEFORE I tried your fix I see the following with your race code in my environment. Note I took out some of the traces to make it easier to read and added a "START" and "STOP" trace. 

This is the results of 5 runs. You can see it is highly variable and includes a strange exception on one of them.

```
START
threads in main: 4
threads in main: 6
STOP


START
threads in main: 4
threads in main: 5
STOP


START
threads in main: 4
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./race.py", line 39, in run_consumer
    consumer = topic.get_simple_consumer("test")
  File "/pykafka/pykafka/topic.py", line 147, in get_simple_consumer
    consumer_group=consumer_group, **kwargs)
  File "/pykafka/pykafka/simpleconsumer.py", line 189, in __init__
    self.start()
  File "/pykafka/pykafka/simpleconsumer.py", line 211, in start
    self.fetch_offsets()
  File "/pykafka/pykafka/simpleconsumer.py", line 446, in fetch_offsets
    res = self._offset_manager.fetch_consumer_group_offsets(self._consumer_group, reqs)
  File "/pykafka/pykafka/broker.py", line 348, in fetch_consumer_group_offsets
    return self._offsets_channel_req_handler.request(req).get(OffsetFetchResponse)
  File "/pykafka/pykafka/handlers.py", line 55, in get
    raise self.error
SocketDisconnectedError

threads in main: 8
STOP


START
threads in main: 4
threads in main: 9
STOP


START
threads in main: 4
threads in main: 5
STOP
```

Now I'm going to try to merge in your branch and see what happens.  Will report back, stay tuned.

**Comment by emmett9001** [comment]
Yes, that's exactly what I saw that led me to the patch.

**Comment by zsimpson** [comment]
OK. Now with your fix merged. Seems like it works.

```
START
threads in main: 4
threads in main: 5
STOP


START
threads in main: 4
threads in main: 5
STOP


START
threads in main: 4
threads in main: 5
STOP


START
threads in main: 4
threads in main: 5
STOP


START
threads in main: 4
threads in main: 5
STOP
```

Now I'm going to go try my own tests and see if it fixed for that case.

**Comment by zsimpson** [comment]
In my code its still thread leaking. Are you sure about that one extra thread being normal in the race.py you sent?

**Comment by emmett9001** [comment]
Yes, it should be only one extra thread regardless of how many consumers are started/stopped. This happens because starting a consumer causes another thread to be started in the `Broker`, which is persistent in the `KafkaClient`. It's lazily opening a socket connection to the kafka server for the purpose of committing offsets.

**Comment by zsimpson** [comment]
Oh I see... the problem is now with producer. It is leaking too. I changed your race.py like this:

```
def run_consumer():
    topic = client.topics['testtopic_replicated2']
    consumer = topic.get_simple_consumer("test")
    producer = topic.get_producer()
    consumer.stop()
    producer.stop()
    time.sleep(2)
```

Note, I added a "producer" and a producer.stop()

Now your test traces out the following:
```
START
threads in main: 4
threads in main: 45
STOP
```

So there's 40 threads getting stranded. That's 2 per call. Which is exactly what I'm seeing in my other code.

**Comment by emmett9001** [comment]
Are you running a two-broker cluster? If so, this makes perfect sense and should be solved by [this pull request](https://github.com/Parsely/pykafka/pull/254). (I'm also assuming you're testing against current master).

**Comment by zsimpson** [comment]
Yes, 2 broker cluster. I am testing against my merge of your last PR, i.e. branch bugfix/threadleak. I will go merge in feature/producer_broker_failure and see if that fixes it.

**Comment by emmett9001** [comment]
I just pushed a fix that should ensure that `feature/producer_broker_failure` fixes this issue - make sure you pull the latest.

**Comment by zsimpson** [comment]
I think I pulled things correctly.. (Might have messed up somehow!). You can look at the graph and check:

https://github.com/Parsely/pykafka/network

I'm using the branch on our appsoma fork called "tryout_feature_producer_broker_failure". It appears to merge in both of your recent branches.

But I'm still getting this from my modified race.py (the one that include producer)

```
START
threads in main: 4
threads in main: 40
STOP

START
threads in main: 4
threads in main: 41
STOP

START
threads in main: 4
threads in main: 41
STOP

START
threads in main: 4
threads in main: 39
STOP
```

**Comment by emmett9001** [comment]
Hmm, guess i'll have to take a closer look. Might not get to it until Tuesday.

**Comment by zsimpson** [comment]
Okay. Thanks for the help so far! :-)

**Comment by yungchin** [comment]
I was just testing this against #258 and that seems to address the consumer thread leak reported here, but not the producer thread leak.

**Comment by zsimpson** [comment]
Emmett, thanks for the help so far. Is there anything I can do to help you with this issue?

**Comment by yungchin** [comment]
@emmett9001 it just occurred to me that the queue readers in the producer have no way of checking `self._running`. That probably explains the producer thread leaks, at least in part.

**Comment by emmett9001** [comment]
@zsimpson Current master fixes this issue by stopping producer threads in `Producer.stop()`. It takes a few seconds for the threads to full exit, but you're in good shape if you use the context manager or manually call `Producer.stop()`.

Let me know if this works for you and if you have any other issues.
